-- Create database and schema for RAG chatbot
CREATE DATABASE IF NOT EXISTS RAG_CHAT_BOT_DB;
USE DATABASE RAG_CHAT_BOT_DB;
CREATE SCHEMA IF NOT EXISTS PUBLIC;
USE SCHEMA PUBLIC;

-- Create table for storing documents
CREATE TABLE IF NOT EXISTS DOCUMENTS (
    ID NUMBER AUTOINCREMENT PRIMARY KEY,
    FILENAME VARCHAR(500) NOT NULL,
    CONTENT TEXT NOT NULL,
    METADATA VARIANT,
    UPLOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PROCESSED BOOLEAN DEFAULT FALSE
);

-- Create table for storing document chunks
CREATE TABLE IF NOT EXISTS DOCUMENT_CHUNKS (
    ID NUMBER AUTOINCREMENT PRIMARY KEY,
    DOCUMENT_ID NUMBER NOT NULL,
    CHUNK_TEXT TEXT NOT NULL,
    CHUNK_INDEX NUMBER NOT NULL,
    CHUNK_METADATA VARIANT,
    EMBEDDING ARRAY,
    FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENTS(ID)
);

-- Create table for storing chat history
CREATE TABLE IF NOT EXISTS CHAT_HISTORY (
    ID NUMBER AUTOINCREMENT PRIMARY KEY,
    SESSION_ID VARCHAR(100) NOT NULL,
    USER_QUESTION TEXT NOT NULL,
    BOT_RESPONSE TEXT NOT NULL,
    RETRIEVED_DOCUMENTS VARIANT,
    TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create Cortex Search service for semantic search
CREATE OR REPLACE CORTEX SEARCH SERVICE DOCUMENT_SEARCH_SERVICE
ON CHUNK_TEXT
WAREHOUSE = COMPUTE_WH
TARGET_LAG = '1 minute'
AS (
    SELECT 
        ID,
        CHUNK_TEXT,
        CHUNK_METADATA,
        DOCUMENT_ID
    FROM DOCUMENT_CHUNKS
); 